### ISSUE TITLE
Cannot parse 5 sides

### ISSUE THREAD

**Issue by supaflyENJOY** [jedmao/parse-css-sides#1]
Hello, Jed! 
`parse-css-sides` currently has a bug:
1. If you have an input: `5px 10px !important` it returns an invalid object:
`{ top: '5px', right: '10px', bottom: '!important', left: '10px' }`
2. If you have an input: `5px 10px 6px 7px !important` it throws an error:
`Cannot parse 5 sides`

Do you accept pull requests?
I think, we can check after splitting that latest element in array contains `!important` and save some flag for return object

**Comment by jedmao** [comment]
You're lucky I was bored stiff in a hospital today. Enjoy version 3.0.1!

**Comment by supaflyENJOY** [comment]
@jedmao great! Thank you so much!
